micronaut:
  application:
    name: campsite

  server:
    host: ${SERVER_HOST:0.0.0.0}
    port: ${SERVER_PORT:8080}
    cors:
      enabled: true

  security:
    enabled: false


  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

endpoints:
  health:
    enabled: true
    sensitive: false
    jdbc:
      enabled: true
    disk-space:
      enabled: false
    discovery-client:
      enabled: false
    details-visible: ANONYMOUS

jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
    indentOutput: true

datasources:
  default:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driverClassName: ${JDBC_DRIVER}
    schema-generate: NONE
    maximum-pool-size: ${MAX_DB_POOL_SIZE}

db:
  schema:
    version: '1.0'

redis:
  uri: ${REDIS_URI}

logger:
  levels:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    com:
      upgrade: ${CAMPSITE_LOGGING_LEVEL:INFO}
    io:
      micronaut:
        http:
          server:
            netty:
              NettyHttpServer:  ${CAMPSITE_LOGGING_LEVEL:INFO}  # Received Request log